---
title: "Challenge_1_sales_report"
author: "LukasMackel"
date: "2024-07-17"
output:
  html_document:
    code_folding: none
    df_print: paged
    highlight: tango
    number_sections: yes
    theme: flatly
    toc: yes
    toc_depth: 2
  pdf_document:
    toc: yes
    toc_depth: '2'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    eval = TRUE,
    message = FALSE,
    warning = FALSE,
    dpi = 300,
    fig.align = "center"
    )

# See Options: knitr::opts_chunk$get()
```

```{r, echo=FALSE}
knitr::convert_chunk_header("reporting_rmarkdown.Rmd", output = "reporting_rmarkdown.qmd")
is_html <- knitr::opts_knit$get("rmarkdown.pandoc.to") == "html"
is_pdf <- knitr::opts_knit$get("rmarkdown.pandoc.to") == "pdf"
```


```{r, echo=FALSE}

# eval = FALSE (Show code, but don't run, no output)
# echo = FALSE (Don't show code, but run, show output)
# results = "hide" (Show code, and run, but don't show output)

# Load Libraries
library(tidyverse)
library(plotly)
library(dplyr)
# Main
library(tidyverse)
library(lubridate)
library(shiny)
library(ggplot2)
library(ggplot2)
library(dplyr)
library(lubridate)
library(plotly)
library(scales)
library(forcats)

library(scales)
library(forcats)




bikes_tbl      <- readRDS("01_data/bikes_tbl.rds")
bikeshops_tbl  <- readRDS("01_data/bikeshops_tbl.rds")
orderlines_tbl <- readRDS("01_data/orderlines_tbl.rds")

bike_orderlines_tbl <- orderlines_tbl %>%
    left_join(bikes_tbl,     by = c("product_id" = "bike_id")) %>%
    left_join(bikeshops_tbl, by = c("customer_id" = "bikeshop_id")) %>%
    
    # Add the total price
    mutate(total_price = price_euro * quantity)

format_to_euro <- function(x, suffix = " €") {

  scales::dollar(x,
                 suffix       = suffix,
                 prefix       = "",
                 big.mark     = ".",
                 decimal.mark = ",")
}
euro_format <- function(scale        = 1,
                        prefix       = "",
                        suffix       = " €",
                        big.mark     = ".",
                        decimal.mark = ",") {

  scales::dollar_format(suffix       = suffix,
                        prefix       = prefix,
                        big.mark     = big.mark,
                        decimal.mark = decimal.mark,
                        scale        = scale)

}

```

# Total Sales Charts {.tabset} 

## Quarterly Sales Trends
```{r, echo=FALSE }

if (is_pdf) {
 print("Hier ist ein pdf text") 
}



total_sales_m_tbl <- bike_orderlines_tbl %>%
  dplyr::select(order_date, total_price) %>%

  mutate(date_rounded = floor_date(order_date, unit = "quarter")) %>%

  group_by(date_rounded) %>%
  summarise(total_sales = sum(total_price)) %>%
  ungroup() %>%

  mutate(label_text = str_glue("Sales: {format_to_euro(total_sales)}
                                 Date: {date_rounded %>% format('%B %Y')}"))


g1 <- total_sales_m_tbl %>%
  ggplot(aes(x = date_rounded, y = total_sales)) +

  # Geoms
  geom_point() +
  geom_smooth(method = "loess", span = 0.2) +

  # Formatting
  
  # Convert scale to euro format
  scale_y_continuous(labels = euro_format()) +
  
  # Make sure 0 will always be shown (even if the data is far away)
  expand_limits(y = 0) +
  
  labs(
    title = "Total Sales",
    y = "Revenue (EUR)",
    x = ""
  )

g1

```

## Montly Sales Trends
```{r, echo=FALSE }

  


total_sales_m_tbl <- bike_orderlines_tbl %>%

  dplyr::select(order_date, total_price) %>%

  mutate(date_rounded = floor_date(order_date, unit = "month")) %>%

  group_by(date_rounded) %>%
  summarise(total_sales = sum(total_price)) %>%
  ungroup() %>%

  mutate(label_text = str_glue("Sales: {format_to_euro(total_sales)}
                                 Date: {date_rounded %>% format('%B %Y')}"))


g1 <- total_sales_m_tbl %>%
  ggplot(aes(x = date_rounded, y = total_sales)) +

  # Geoms
  geom_point() +
  geom_smooth(method = "loess", span = 0.2) +

  # Formatting
  
  # Convert scale to euro format
  scale_y_continuous(labels = euro_format()) +
  
  # Make sure 0 will always be shown (even if the data is far away)
  expand_limits(y = 0) +
  
  labs(
    title = "Total Sales",
    y = "Revenue (EUR)",
    x = ""
  )

g1

```

## Weekly Sales Trends
```{r, echo=FALSE }



total_sales_m_tbl <- bike_orderlines_tbl %>%

  dplyr::select(order_date, total_price) %>%

  mutate(date_rounded = floor_date(order_date, unit = "week")) %>%

  group_by(date_rounded) %>%
  summarise(total_sales = sum(total_price)) %>%
  ungroup() %>%

  mutate(label_text = str_glue("Sales: {format_to_euro(total_sales)}
                                 Date: {date_rounded %>% format('%B %Y')}"))


g1 <- total_sales_m_tbl %>%
  ggplot(aes(x = date_rounded, y = total_sales)) +

  # Geoms
  geom_point() +
  geom_smooth(method = "loess", span = 0.2) +

  # Formatting
  
  # Convert scale to euro format
  scale_y_continuous(labels = euro_format()) +
  
  # Make sure 0 will always be shown (even if the data is far away)
  expand_limits(y = 0) +
  
  labs(
    title = "Total Sales",
    y = "Revenue (EUR)",
    x = ""
  )

g1

```

# Category Sales Charts {.tabset} 

## Road {.tabset}

### Quarterly

```{r, echo=FALSE}
# 2.3 Plot Categories Function ----

plot_categories <- function(category_1 = "Road", category_2 = "All",
                            unit = "quarter", date_format = "%Y",
                            ncol = 1, scales = "free_y",
                            interactive = FALSE,plot_height = 5000) {

  # Handle Data
  data_tbl <- bike_orderlines_tbl %>%
    dplyr::select(order_date, category_1, category_2, total_price) %>%
    mutate(date_rounded = floor_date(order_date, unit = unit)) %>%
    group_by(date_rounded, category_1, category_2) %>%
    summarise(total_sales = sum(total_price)) %>%
    ungroup() %>%
    mutate(label_text = str_glue("Sales: {format_to_euro(total_sales)}
                                 Date: {date_rounded %>% format(date_format)}")) %>%
    mutate(category_2 = as_factor(category_2) %>%
             fct_reorder2(date_rounded, total_sales))

  # Handle Inputs
  cat_1_text <- str_to_lower(category_1)
  cat_2_text <- str_to_lower(category_2)

  # Create Filter Logic
  if (cat_1_text != "all") {
    data_tbl <- data_tbl %>%
      filter(category_1 %>%
               str_to_lower() %>%
               str_detect(pattern = cat_1_text))
  }

  if (cat_2_text != "all") {
    data_tbl <- data_tbl %>%
      filter(category_2 %>%
               str_to_lower() %>%
               str_detect(pattern = cat_2_text))
  }

  # Make Plot
  g2 <- data_tbl %>%
    ggplot(aes(x = date_rounded, y = total_sales, color = category_2)) +
    geom_point(aes(text = label_text), color = "#2c3e50") +
    geom_smooth(method = "loess", span = 0.2) +
    facet_wrap(~ category_2, scales = scales, ncol = ncol) +
    # Formatting
    expand_limits(y = 0) +
    theme(legend.position = "none",
          axis.text = element_text(size = 18),        # Schriftgröße der Achsentexte
          axis.title = element_text(size = 18),       # Schriftgröße der Achsentitel
          plot.title = element_text(size = 25), # Schriftgröße und Stil des Plottitels
          strip.text.x = element_text(size = 20, margin = margin(10, 10, 10, 10, unit = "pt")),
          plot.margin = unit(c(1, 1, 1, 1), "cm"),
          panel.spacing = unit(0.01, "lines")) +
    scale_y_continuous(labels = scales::number_format(scale = 1e-3, suffix = "K €")) +
    labs(
      title = "Sales By Category 2",
      y = "", x = ""
    )

}

plot <- plot_categories(category_1 = "Road", unit = "quarter", date_format = "%Y", ncol = 1, scales = "free_y", interactive = FALSE)

# Speichern des Plots mit explizit größerer Höhe
ggsave("PDFPlots/plotQuarterlyRoad.png", plot = plot, height = 10, width = 10)  # Höhe und Breite anpassen

img <- png::readPNG("PDFPlots/plotQuarterlyRoad.png")
grid::grid.raster(img)

```

### Montly 
```{r, echo=FALSE}
plot_categories <- function(category_1 = "Road", category_2 = "All",
                            unit = "month", date_format = "%Y",
                            ncol = 1, scales = "free_y",
                            interactive = FALSE, plot_height = 1200) {

  # Handle Data
  data_tbl <- bike_orderlines_tbl %>%
    dplyr::select(order_date, category_1, category_2, total_price) %>%
    mutate(date_rounded = floor_date(order_date, unit = unit)) %>%
    group_by(date_rounded, category_1, category_2) %>%
    summarise(total_sales = sum(total_price)) %>%
    ungroup() %>%
    mutate(label_text = str_glue("Sales: {format_to_euro(total_sales)}
                                 Date: {date_rounded %>% format(date_format)}")) %>%
    mutate(category_2 = as_factor(category_2) %>%
             fct_reorder2(date_rounded, total_sales))

  # Handle Inputs
  cat_1_text <- str_to_lower(category_1)
  cat_2_text <- str_to_lower(category_2)

  # Create Filter Logic
  if (cat_1_text != "all") {
    data_tbl <- data_tbl %>%
      filter(category_1 %>%
               str_to_lower() %>%
               str_detect(pattern = cat_1_text))
  }

  if (cat_2_text != "all") {
    data_tbl <- data_tbl %>%
      filter(category_2 %>%
               str_to_lower() %>%
               str_detect(pattern = cat_2_text))
  }

  # Make Plot
  g2 <- data_tbl %>%
    ggplot(aes(x = date_rounded, y = total_sales, color = category_2)) +
    # Geoms
    geom_point(aes(text = label_text), color = "#2c3e50") +
    geom_smooth(method = "loess", span = 0.2, se = TRUE) +
    facet_wrap(~ category_2, scales = scales, ncol = ncol) +
    # Formatting
    expand_limits(y = 0) +
    theme(legend.position = "none",
          axis.text = element_text(size = 18),        # Schriftgröße der Achsentexte
          axis.title = element_text(size = 18),       # Schriftgröße der Achsentitel
          plot.title = element_text(size = 25), # Schriftgröße und Stil des Plottitels
          strip.text.x = element_text(size = 20, margin = margin(10, 10, 10, 10, unit = "pt")),
          plot.margin = unit(c(1, 1, 1, 1), "cm"),
          panel.spacing = unit(0.01, "lines")) +
    scale_y_continuous(labels = scales::number_format(scale = 1e-3, suffix = "K €")) +
    labs(
      title = "Sales By Category 2",
      y = "", x = ""
    )

  
}

# Beispiel-Aufruf des modifizierten Codes
plot <- plot_categories(category_1 = "Road", unit = "month", date_format = "%Y", ncol = 1, scales = "free_y", interactive = FALSE, plot_height = 1000)

# Speichern des Plots mit explizit größerer Höhe
ggsave("PDFPlots/plotMontlyRoad.png", plot = plot, height = 15, width = 15)  # Höhe und Breite anpassen

img <- png::readPNG("PDFPlots/plotMontlyRoad.png")
grid::grid.raster(img)

```

### Weekly 
```{r, echo=FALSE}
plot_categories <- function(category_1 = "Road", category_2 = "All",
                            unit = "week", date_format = "%Y",
                            ncol = 1, scales = "free_y",
                            interactive = FALSE, plot_height = 20000) {

  # Handle Data
  data_tbl <- bike_orderlines_tbl %>%
    dplyr::select(order_date, category_1, category_2, total_price) %>%
    mutate(date_rounded = floor_date(order_date, unit = unit)) %>%
    group_by(date_rounded, category_1, category_2) %>%
    summarise(total_sales = sum(total_price)) %>%
    ungroup() %>%
    mutate(label_text = str_glue("Sales: {format_to_euro(total_sales)}
                                 Date: {date_rounded %>% format(date_format)}")) %>%
    mutate(category_2 = as_factor(category_2) %>%
             fct_reorder2(date_rounded, total_sales))

  # Handle Inputs
  cat_1_text <- str_to_lower(category_1)
  cat_2_text <- str_to_lower(category_2)

  # Create Filter Logic
  if (cat_1_text != "all") {
    data_tbl <- data_tbl %>%
      filter(category_1 %>%
               str_to_lower() %>%
               str_detect(pattern = cat_1_text))
  }

  if (cat_2_text != "all") {
    data_tbl <- data_tbl %>%
      filter(category_2 %>%
               str_to_lower() %>%
               str_detect(pattern = cat_2_text))
  }

  # Make Plot
  g2 <- data_tbl %>%
    ggplot(aes(x = date_rounded, y = total_sales, color = category_2)) +
    # Geoms
    geom_point(aes(text = label_text), color = "#2c3e50") +
    geom_smooth(method = "loess", span = 0.2, se = TRUE) +
    facet_wrap(~ category_2, scales = scales, ncol = ncol) +
    # Formatting
    expand_limits(y = 0) +
    theme(legend.position = "none",
          axis.text = element_text(size = 18),        # Schriftgröße der Achsentexte
          axis.title = element_text(size = 18),       # Schriftgröße der Achsentitel
          plot.title = element_text(size = 25), # Schriftgröße und Stil des Plottitels
          strip.text.x = element_text(size = 20, margin = margin(10, 10, 10, 10, unit = "pt")),
          plot.margin = unit(c(1, 1, 1, 1), "cm"),
          panel.spacing = unit(0.003, "lines")) +
    scale_y_continuous(labels = scales::number_format(scale = 1e-3, suffix = "K €")) +
    labs(
      title = "Sales By Category 2",
      y = "", x = ""
    )

  # Static Vs Interactive Logic
  if (interactive) {
    return(ggplotly(g2, tooltip = "text") %>% layout(height = plot_height))
  } else {
    return(g2)
  }
}

# Beispiel-Aufruf des modifizierten Codes
plot <- plot_categories(category_1 = "Road", unit = "week", date_format = "%Y", ncol = 1, scales = "free_y", interactive = FALSE, plot_height = 20000)

# Speichern des Plots mit explizit größerer Höhe
ggsave("PDFPlots/plotWeeklyRoad.png", plot = plot, height = 10, width = 10)  # Höhe und Breite anpassen

img <- png::readPNG("PDFPlots/plotWeeklyRoad.png")
grid::grid.raster(img)

```

## Mountain {.tabset}

### Quarterly
```{r, echo=FALSE}
plot_categories <- function(category_1 = "Mountain", category_2 = "All",
                            unit = "quarter", date_format = "%Y",
                            ncol = 1, scales = "free_y",
                            interactive = FALSE, plot_height = 1500) {

  # Handle Data
  data_tbl <- bike_orderlines_tbl %>%
    dplyr:: select(order_date, category_1, category_2, total_price) %>%
    mutate(date_rounded = floor_date(order_date, unit = unit)) %>%
    group_by(date_rounded, category_1, category_2) %>%
    summarise(total_sales = sum(total_price)) %>%
    ungroup() %>%
    mutate(label_text = str_glue("Sales: {format_to_euro(total_sales)}
                                 Date: {date_rounded %>% format(date_format)}")) %>%
    mutate(category_2 = as_factor(category_2) %>%
             fct_reorder2(date_rounded, total_sales))

 

  # Handle Inputs
  cat_1_text <- str_to_lower(category_1)
  cat_2_text <- str_to_lower(category_2)

  # Create Filter Logic
  if (cat_1_text != "all") {
    data_tbl <- data_tbl %>%
      filter(category_1 %>%
               str_to_lower() %>%
               str_detect(pattern = cat_1_text))
  }

  if (cat_2_text != "all") {
    data_tbl <- data_tbl %>%
      filter(category_2 %>%
               str_to_lower() %>%
               str_detect(pattern = cat_2_text))
  }

  

  # Check if data is available after filtering
  if (nrow(data_tbl) == 0) {
    stop("No data available for the selected filters.")
  }

  # Make Plot
  g2 <- data_tbl %>%
    ggplot(aes(x = date_rounded, y = total_sales, color = category_2)) +
    # Geoms
    geom_point(aes(text = label_text), color = "#2c3e50") +
    geom_smooth(method = "loess", span = 0.2, se = TRUE) +
    facet_wrap(~ category_2, scales = scales, ncol = ncol) +
    # Formatting
    expand_limits(y = 0) +
    theme(legend.position = "none",
          axis.text = element_text(size = 18),        # Schriftgröße der Achsentexte
          axis.title = element_text(size = 18),       # Schriftgröße der Achsentitel
          plot.title = element_text(size = 25), # Schriftgröße und Stil des Plottitels
          strip.text.x = element_text(size = 20, margin = margin(10, 10, 10, 10, unit = "pt")),
          plot.margin = unit(c(1, 1, 1, 1), "cm"),
          panel.spacing = unit(0.2, "lines")) +
    scale_y_continuous(labels = scales::number_format(scale = 1e-3, suffix = "K €")) +
    labs(
      title = "Sales By Category 2",
      y = "", x = ""
    )

  # Static Vs Interactive Logic
  if (interactive) {
    return(ggplotly(g2, tooltip = "text") %>% layout(height = plot_height))
  } else {
    return(g2)
  }
}

# Beispiel-Aufruf des modifizierten Codes
plot <- plot_categories(category_1 = "Mountain", unit = "quarter", date_format = "%Y", ncol = 1, scales = "free_y", interactive = FALSE, plot_height = 1500)

# Speichern des Plots mit explizit größerer Höhe
ggsave("PDFPlots/plotQuarterlyMountain.png", plot = plot, height = 10, width = 10)  # Höhe und Breite anpassen

img <- png::readPNG("PDFPlots/plotQuarterlyMountain.png")
grid::grid.raster(img)
```

### Monthly
```{r, echo=FALSE}
plot_categories <- function(category_1 = "Mountain", category_2 = "All",
                            unit = "month", date_format = "%Y-%m",
                            ncol = 1, scales = "free_y",
                            interactive = FALSE, plot_height = 1500) {

  # Handle Data
  data_tbl <- bike_orderlines_tbl %>%
    dplyr::select(order_date, category_1, category_2, total_price) %>%
    mutate(date_rounded = floor_date(order_date, unit = unit)) %>%
    group_by(date_rounded, category_1, category_2) %>%
    summarise(total_sales = sum(total_price)) %>%
    ungroup() %>%
    mutate(label_text = str_glue("Sales: {format_to_euro(total_sales)}
                                 Date: {date_rounded %>% format(date_format)}")) %>%
    mutate(category_2 = as_factor(category_2) %>%
             fct_reorder2(date_rounded, total_sales))

 

  # Handle Inputs
  cat_1_text <- str_to_lower(category_1)
  cat_2_text <- str_to_lower(category_2)

  # Create Filter Logic
  if (cat_1_text != "all") {
    data_tbl <- data_tbl %>%
      filter(category_1 %>%
               str_to_lower() %>%
               str_detect(pattern = cat_1_text))
  }

  if (cat_2_text != "all") {
    data_tbl <- data_tbl %>%
      filter(category_2 %>%
               str_to_lower() %>%
               str_detect(pattern = cat_2_text))
  }



  # Check if data is available after filtering
  if (nrow(data_tbl) == 0) {
    stop("No data available for the selected filters.")
  }

  # Make Plot
  g2 <- data_tbl %>%
    ggplot(aes(x = date_rounded, y = total_sales, color = category_2)) +
    # Geoms
    geom_point(aes(text = label_text), color = "#2c3e50") +
    geom_smooth(method = "loess", span = 0.2, se = TRUE) +
    facet_wrap(~ category_2, scales = scales, ncol = ncol) +
    # Formatting
    expand_limits(y = 0) +
    theme(legend.position = "none",
          axis.text = element_text(size = 18),        # Schriftgröße der Achsentexte
          axis.title = element_text(size = 18),       # Schriftgröße der Achsentitel
          plot.title = element_text(size = 25), # Schriftgröße und Stil des Plottitels
          strip.text.x = element_text(size = 20, margin = margin(10, 10, 10, 10, unit = "pt")),
          plot.margin = unit(c(1, 1, 1, 1), "cm"),
          panel.spacing = unit(0.01, "lines")) +  # Increase spacing between panels
    scale_y_continuous(labels = scales::number_format(scale = 1e-3, suffix = "K €")) +
    labs(
      title = "Sales By Category 2",
      y = "", x = ""
    )

  # Static Vs Interactive Logic
  if (interactive) {
    return(ggplotly(g2, tooltip = "text") %>% layout(height = plot_height))
  } else {
    return(g2)
  }
}

# Beispiel-Aufruf des modifizierten Codes
plot <- plot_categories(category_1 = "Mountain", unit = "month", date_format = "%Y-%m", ncol = 1, scales = "free_y", interactive = FALSE, plot_height = 3000)

# Speichern des Plots mit explizit größerer Höhe
ggsave("PDFPlots/plotMonthlyMountain.png", plot = plot, height = 10, width = 10)  # Höhe und Breite anpassen

img <- png::readPNG("PDFPlots/plotMonthlyMountain.png")
grid::grid.raster(img)


```

### Weekly
```{r, echo=FALSE}



plot_categories <- function(category_1 = "Mountain", category_2 = "All",
                            unit = "week", date_format = "%Y",
                            ncol = 1, scales = "free_y",
                            interactive = FALSE, plot_height = 3000) {

  # Handle Data
  data_tbl <- bike_orderlines_tbl %>%
    dplyr::select(order_date, category_1, category_2, total_price) %>%
    mutate(date_rounded = floor_date(order_date, unit = unit)) %>%
    group_by(date_rounded, category_1, category_2) %>%
    summarise(total_sales = sum(total_price)) %>%
    ungroup() %>%
    mutate(label_text = str_glue("Sales: {format_to_euro(total_sales)}
                                 Date: {date_rounded %>% format(date_format)}")) %>%
    mutate(category_2 = as_factor(category_2) %>%
             fct_reorder2(date_rounded, total_sales))

  

  # Handle Inputs
  cat_1_text <- str_to_lower(category_1)
  cat_2_text <- str_to_lower(category_2)

  # Create Filter Logic
  if (cat_1_text != "all") {
    data_tbl <- data_tbl %>%
      filter(category_1 %>%
               str_to_lower() %>%
               str_detect(pattern = cat_1_text))
  }

  if (cat_2_text != "all") {
    data_tbl <- data_tbl %>%
      filter(category_2 %>%
               str_to_lower() %>%
               str_detect(pattern = cat_2_text))
  }



  # Check if data is available after filtering
  if (nrow(data_tbl) == 0) {
    stop("No data available for the selected filters.")
  }

  # Make Plot
  g2 <- data_tbl %>%
    ggplot(aes(x = date_rounded, y = total_sales, color = category_2)) +
    # Geoms
    geom_point(aes(text = label_text), color = "#2c3e50") +
    geom_smooth(method = "loess", span = 0.2, se = TRUE) +
    facet_wrap(~ category_2, scales = scales, ncol = ncol) +
    # Formatting
    expand_limits(y = 0) +
    theme(legend.position = "none",
          axis.text = element_text(size = 18),        # Schriftgröße der Achsentexte
          axis.title = element_text(size = 18),       # Schriftgröße der Achsentitel
          plot.title = element_text(size = 25), # Schriftgröße und Stil des Plottitels
          strip.text.x = element_text(size = 20, margin = margin(10, 10, 10, 10, unit = "pt")),
          plot.margin = unit(c(1, 1, 1, 1), "cm"),
          panel.spacing = unit(0.1, "lines")) +  # Increase spacing between panels
    scale_y_continuous(labels = scales::number_format(scale = 1e-3, suffix = "K €")) +
    labs(
      title = "Sales By Category 2",
      y = "", x = ""
    )

  # Static Vs Interactive Logic
  if (interactive) {
    return(ggplotly(g2, tooltip = "text") %>% layout(height = plot_height))
  } else {
    return(g2)
  }
}

# Beispiel-Aufruf des modifizierten Codes
plot <- plot_categories(category_1 = "Mountain", unit = "week", date_format = "%Y", ncol = 1, scales = "free_y", interactive = FALSE, plot_height = 3000)


# Speichern des Plots mit explizit größerer Höhe
ggsave("PDFPlots/plotWeeklyMountain.png", plot = plot, height = 15, width = 15)  # Höhe und Breite anpassen

img <- png::readPNG("PDFPlots/plotWeeklyMountain.png")
grid::grid.raster(img)
```



